### ISSUE TITLE
Enhancement: Improve the game start

### ISSUE THREAD

**Issue by DarkFalc0n** [DarkFalc0n/smashout#11]
Currently, the ball falls from a height abruptly at the start of the game. Improve it such that the ball rests on the base at the start and can be shot by clicking and thus starting the game.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under jwoc so i request you to please assign me

**Comment by vk20july** [comment]
sir I want to work on this issue under JWOC
Sir, the above person has also requested for assign to other issue of this project as well, so could you please assign him that issue
and assign me this issue it will be fair for both of us

**Comment by DarkFalc0n** [comment]
@Hritik1503 would you like to hand this issue over to @vk20july. I already assigned you to two other issues ?

**Comment by vk20july** [comment]
@DarkFalc0n though I am more confident in this task ```Track the score and displaying point table``` but I would also like to do this task

**Comment by vk20july** [comment]
@DarkFalc0n sir made a PR kindly review
