### ISSUE TITLE
Create a function to end the game.

### ISSUE THREAD

**Issue by Anshkanungo** [DarkFalc0n/smashout#2]
Creating a function where if ball hits the bottom surface of the screen, the game will end and "Game is over" message will be displayed.

**Comment by Anshkanungo** [comment]
Hey @DarkFalc0n, I want to work on this Issue under JWOC.

**Comment by DarkFalc0n** [comment]
@Anshkanungo I made some changes to the project structure, so make sure to pull the latest changes after syncing your fork.
There is a blank function called gameOver() that gets triggered when the ball touches the floor, but feel free to make changes as you wish.

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC
