### ISSUE TITLE
Track the score and displaying points table 

### ISSUE THREAD

**Issue by Ashishdode** [DarkFalc0n/smashout#3]
It will basically show the points you have scored and will track it......if you break records

**Comment by Ashishdode** [comment]
I want to work on this issue under JWOC

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by DarkFalc0n** [comment]
@Ashishdode go ahead

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by DarkFalc0n** [comment]
@vk20july go on
