### ISSUE TITLE
Make the bricks disappear upon scoring a hit.

### ISSUE THREAD

**Issue by DarkFalc0n** [DarkFalc0n/smashout#4]
Currently, the bricks have no effect on collision with the ball. Make them disappear upon contact with the ball.

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by vk20july** [comment]
Can I do?

**Comment by vk20july** [comment]
@DarkFalc0n sir can you please assign this issue to me

**Comment by DarkFalc0n** [comment]
@vk20july Go ahead.
