### ISSUE TITLE
Add a instruction text for the controls.

### ISSUE THREAD

**Issue by DarkFalc0n** [DarkFalc0n/smashout#9]
Add a text line below the game window that contains the game control instructions.

**Comment by vk20july** [comment]
so basically we have to write what we have to do in this game?

**Comment by vk20july** [comment]
Although I want to work on this issue under JWOC

**Comment by DarkFalc0n** [comment]
Hey @vk20july you just need to specify that the game uses the arrow keys to move the base. I would recommend you to use the key icons so that the instruction looks good.
Icon example: 
![image](https://user-images.githubusercontent.com/59203815/221127490-293b2485-7a51-45cc-93da-9242818dadf0.png)
But make sure that the instruction is descriptive like :
Use (icon) to move the base left and (icon) to move it to the right.

**Comment by vk20july** [comment]
got it
